"""test_vertex_rule.py — Phase D3 pinned: the wiring generated by rule."""

from sm_wiring import TARGET_EDGES
from vertex_rule import generate_edges, generate_without, reads_other


def test_the_generator_reproduces_the_plate_exactly():
    """One criterion + one attribute table = all 45 cells, no case-lists."""
    assert generate_edges() == TARGET_EDGES


def test_the_self_column_is_the_first_rung_criterion():
    """Self-loop iff the carrier reads what it carries: W, g, H, G yes;
    photon and Z (the net-0 face) NO — no ZZZ vertex, generated."""
    gen = generate_edges()
    for x in ("W", "g", "H", "G"):
        assert frozenset([x]) in gen
    for x in ("A", "Z", "Q", "L", "N"):
        assert frozenset([x]) not in gen


def test_the_assembled_cells_are_now_generated():
    """The five EW cells sm_wiring tagged [assembled] fall out of the
    reading rule with no hand assembly."""
    gen = generate_edges()
    for pair in (("W", "Z"), ("W", "H"), ("Z", "H")):
        assert frozenset(pair) in gen
    assert frozenset(["W"]) in gen and frozenset(["H"]) in gen


def test_input_isolation_color_costs_exactly_two_cells():
    """Deleting the color attribute removes exactly {g-Q, g-self} — the
    wiring layer owes the same single input as the content layer."""
    diff = TARGET_EDGES - generate_without("color")
    assert diff == {frozenset(["g", "Q"]), frozenset(["g"])}


def test_notorious_absences_are_generated_absences():
    """No gamma-Z, no gamma-H, no H-nu (never-rounds), no fermion-fermion:
    each absence falls out of the table, none is stipulated."""
    gen = generate_edges()
    for pair in (("A", "Z"), ("A", "H"), ("A", "g"), ("H", "N"),
                 ("Q", "L"), ("Q", "N"), ("L", "N"), ("g", "H")):
        assert frozenset(pair) not in gen
    assert not reads_other("Q", "Q")              # fermions read nothing
