"""
THE HEXAD/TRIAD SPLIT of Z/9Z.   GRADE: FORCED ◆ (the ring structure).

The integers mod 9 split, by their ring structure, into:

  HEXAD = the units (gcd with 9 = 1)        = {1, 2, 4, 5, 7, 8}   (6 elements)
  TRIAD = the maximal ideal (3) = non-units = {0, 3, 6}            (3 elements)

The unit group (Z/9)* is cyclic of order 6, generated by 2: the DOUBLING CYCLE
1 -> 2 -> 4 -> 8 -> 7 -> 5 -> 1  (mod 9), which is exactly the hexad. Antipodes (n and
its negative mod 9) sum to 9. This is the units / maximal-ideal decomposition, forced
by the arithmetic of 9 = 3^2, and it is the structural backbone the framework reads as
the C6 = C2 x C3 of sign and phase.

Source: catalog/THE-FULL-POSITION-INTERNAL Part I (hexad/triad split mod nine);
06-VERIFICATION-LOG (hexad {1,2,4,5,7,8}).
"""
from math import gcd


def test_units_are_the_hexad():
    units = {n for n in range(9) if gcd(n, 9) == 1}
    assert units == {1, 2, 4, 5, 7, 8}
    assert len(units) == 6


def test_maximal_ideal_is_the_triad():
    nonunits = {n for n in range(9) if gcd(n, 9) != 1}
    assert nonunits == {0, 3, 6}
    assert len(nonunits) == 3


def test_doubling_cycle_generates_the_hexad():
    cycle, x = [], 1
    for _ in range(6):
        cycle.append(x)
        x = (x * 2) % 9
    assert cycle == [1, 2, 4, 8, 7, 5]          # the doubling orbit
    assert (cycle[-1] * 2) % 9 == 1              # closes: 2^6 = 1 mod 9
    assert set(cycle) == {1, 2, 4, 5, 7, 8}     # == the units


def test_antipodes_sum_to_nine():
    for a, b in [(1, 8), (2, 7), (4, 5)]:
        assert (a + b) % 9 == 0 and a + b == 9
